### ISSUE TITLE
Anonymous comments

### ISSUE THREAD

**Issue by matteodem** [ARKHAM-Enterprises/meteor-comments-ui#14]
* use accounts-guest
* add a name and email field for anonymous users
* use logins for other services too? (or separate task)
* do not wipe users or add username property to the comments

**Comment by buduguru** [comment]
Hey. I think it is possible to implement using accounts-guest package.

**Comment by matteodem** [comment]
Yep.

**Comment by buduguru** [comment]
What would be nice is to add name and email fields above textarea for guests to fill in. If we just add `accounts-guest` then  username is generated as Guest-#someRandomId, which does not look good. Also, if we clear old guests (there is special function for it(viz `accounts-guest` README)), the according names in comments disappear. What if we could not also add fields for name and email but also save username in a comment document so it will be shown even if user is deleted. I could commit to this issue but I'm not a meteor expert, your skill is much better.

**Comment by matteodem** [comment]
Feel free to help in whatever ways you would like to, I think every help is good and we could both learn from it. I like your ideas, I'll add them to the list

**Comment by buduguru** [comment]
Ok, thanks. Glad it helps. I will fork you repo and add accounts-guest files into subfolder(I think it is the easiest way to merge repos, right?). Will try to play with it.

**Comment by buduguru** [comment]
One more problem that I detected.
When `accounts-guest` package is added I cannot login as normal user (I use `accounts-ui`, so maybe this is the case). Signin/sugnup form just disappears as in case if i'm logged in normally without `accounts-guest`. This is not a problem with `meteor-comments-ui` but we need to take it into account anyway if we want to implement the anonymous feature through 'accounts-guest'. A will try to find out why it does not fit `accounts-ui', maybe will open an issue in their repos.

**Comment by buduguru** [comment]
You know, I thought about this. And...maybe we do not need `accounts-guest` at all? It gives more issues than solves:) I would better just allow non-logged users to post, edit and delete their comments if they indicate email and username(and save the values to comment doc), so it is not necessary to populated Users collection, even temporarily. And this way it would be much easier.  We could, for example, save newly created comments ids into Session variable to control what comments can be deleted and edited by current non-logged user.

**Comment by matteodem** [comment]
I understand your concers, let's have this open for now and if someone of us has the time to implement it we can think about it. Please know though that you use other packages by adding following code to package.js

```javascript
api.use('aldeed:collection2');
```

See here: https://github.com/aldeed/meteor-collection2/blob/master/package.js (aldeed:simple-schema)

**Comment by matteodem** [comment]
Anonymous users now can comment when configured https://github.com/ARKHAM-Enterprises/meteor-comments-ui#anonymous-users
