### ISSUE TITLE
Not all fields can be translated

### ISSUE THREAD

**Issue by buduguru** [ARKHAM-Enterprises/meteor-comments-ui#15]
Following your documentation I could translate only values of these keys:

            'load-more'
            'title'
            'add-button'
            'placeholder-textarea'

'save','edit','remove' stay at default values.

Also there are many other fields that are not indicated in README and cannot be translated ('add-button-reply' etc). And  if I translate  'placeholder-textarea' - only placeholder of the main textarea is translated(text in replies textareas stays default, which is kinda strange).

 I tried to figure out why some values are not translatable though they are implemented in templates the same way as those that are translated OK. If you could give me a hint - I would work on it.

**Comment by matteodem** [comment]
I'll change this to be a Javascript call, something like ```setContent``` to simplify things.

**Comment by matteodem** [comment]
Have a look at the new section please https://github.com/ARKHAM-Enterprises/meteor-comments-ui#text-strings
