### ISSUE TITLE
Strange rendering behavior

### ISSUE THREAD

**Issue by buduguru** [ARKHAM-Enterprises/meteor-comments-ui#16]
Not sure if a problem is with `comments-ui` or my code, but it looks like this:

1. When I open a post with comments for the first time, they are rendered OK (limited quantity and "more comments" button below), 
2. but if I go to another page(list of posts) and come back to that post then I see only "more comments" button.

To dig it:
1. go here http://studycz.meteor.com/faculties and open a post(there is only one) -> comments are rendered OK.
2. then go back and forward - comments are not rendered (there is only "more comments button")

Have no idea why. 
ps I use custom template but thing is the same with default one.
pps added you to private repo with webpage code. maybe you can figure it out.

**Comment by matteodem** [comment]
I feel like this is a bug and I will take my time in the next days to solve it. Thanks for the throughout testing!

**Comment by buduguru** [comment]
Great. Will wait for updates!

**Comment by matteodem** [comment]
Please update to the latest version, it should be fixed.

**Comment by buduguru** [comment]
Unfortunately, patch did not work for me.

Reimplementation example: 
1.  Go to http://studycz.meteor.com/sotsialnaya-set-i-baza-znaniy-studycz-com (comments open OK)
2. Go back and forward - there is only `show more` button

Maybe the issue is caused by 3rd party code?

**Comment by matteodem** [comment]
Tested this locally and it should work now, please update it again and feel free to re-open the ticket if it doesn't work as expected.

**Comment by buduguru** [comment]
It works. Thank you!
