### ISSUE TITLE
Customize schema

### ISSUE THREAD

**Issue by buduguru** [ARKHAM-Enterprises/meteor-comments-ui#17]
For example, I don't need the 200 chars limit in {{content}}. Maybe you could increase it or add a feature to change the limit in config?

**Comment by buduguru** [comment]
Or maybe for now I could just somehow overwrite it using `simple-schema` API in my website code?

**Comment by matteodem** [comment]
I'm not sure about that, you could probably attach the schema again, but right now it's not that easy because of the recursive reply logic that's built in. I'll see if I get time to implement this soonish though.

**Comment by buduguru** [comment]
I use it in production already, so need it asap (I would not want to create a forked package because of that little inconvenience :-) ) Thanks for help in advance.

**Comment by matteodem** [comment]
okay, as you may know I am doing this in my free time and I don't get any profit of this. I think it's awesome that you use it in production, but it won't have any impact on my prioritization :wink:

**Comment by buduguru** [comment]
Yes, I understand, no pressure)

**Comment by matteodem** [comment]
I changed the max length of the comments to be 10000. I will implement this feature at a later time, is that fine?

**Comment by buduguru** [comment]
Yes, thank you!

**Comment by matteodem** [comment]
```Comments.changeSchema``` provides this functionality

**Comment by buduguru** [comment]
Thanks for changes
