### ISSUE TITLE
Custom template helpers error

### ISSUE THREAD

**Issue by loongmxbt** [ARKHAM-Enterprises/meteor-comments-ui#21]
I can only change `<template name="commentsBox">` to `<template name="commentsBoxNew">` and thus can use helper functions such as `take`.

But if I modify `commentsSingleComment` to  `commentsSingleCommentNew`, I cannot use the related helper functions anymore.

I find in `Template.commentsBox.helpers`, there has the following code, but in `Template.commentsSingleComment.helpers`, there doesn't:
```
customTpl: function () {
      if (_.isString(this.customTemplate)) {
        Template[this.customTemplate].inheritsHelpersFrom("commentsBox");
        return Template[this.customTemplate];
      }
    }
```

**Comment by matteodem** [comment]
I dont' understand what your error is, in regards to using the ```customTemplate``` option.

**Comment by superandrew213** [comment]
commentsSingleComment helpers are not available in a custom template. You're only passing over the commentsBox helpers.

    Template[this.customTemplate].inheritsHelpersFrom("commentsBox");

How would you define a custom template for commentsSingleComment?

**Comment by superandrew213** [comment]
This will work

    Template['myCommentsSingleCommentTemplate'].inheritsHelpersFrom('commentsSingleComment');
