### ISSUE TITLE
Ionic template

### ISSUE THREAD

**Issue by epaminond** [ARKHAM-Enterprises/meteor-comments-ui#23]
Hi!

It would be good to have an ionic template for comments-ui package.
I've made some custom templates for ionic views for a project I work on. So I tried to integrate and [made a pull request](https://github.com/ARKHAM-Enterprises/meteor-comments-ui/pull/24) for it. This's how it looks now:

![image](https://cloud.githubusercontent.com/assets/1932290/7441279/18aa0a18-f0e9-11e4-9679-15db8744b1af.png)

**Comment by matteodem** [comment]
Wow! awesome, I'll have a look at it soon!
