### ISSUE TITLE
Custom user avatar

### ISSUE THREAD

**Issue by Neruell** [ARKHAM-Enterprises/meteor-comments-ui#25]
I am a little bit confused, how to use avatar image with comments. I use jparker:gravatar package. I store user's avatars (url/string) in the user's profile. How should I specify what avatar to use? Right now it uses of course the default one, and I know how to specify a different default image, but how to make it use the actual user's avatar?

Also this package doesn't work if used together with utilities:avatar, since bengott:avatar isn't continued for now. Since there is a dependency it will result in multiple "avatar" templates leading to an app crash.

**Comment by Neruell** [comment]
From what I see, this package requires bengott:avatar, which is not continued so you are stuck with the old not updated for now bengott:avatar package. Also that solves my original question, there is no way to set custom avatars, you must use the avatar package.

**Comment by matteodem** [comment]
Oh I forgot to answer. I'll create a new ticket to see for other avatar packages, feel free to give me a hint if you know of anything.

**Comment by Neruell** [comment]
Well, basically all is needed to be done is change the dependency from bengott:avatar to utilities:avatar since they got renamed cause of "owner" change.

So it's still the same github url : https://github.com/bengott/meteor-avatar but just the package itself got renamed to utilities:avatar, nothing else to be done. 

And the issue was that installing both bengott:avatar (because of dependency) and utilities:avatar led to a conflict with same template names, since they are almost exact same packages.

**Comment by matteodem** [comment]
okay, thanks for the info!
