### ISSUE TITLE
Add event hooks 

### ISSUE THREAD

**Issue by alonprince** [ARKHAM-Enterprises/meteor-comments-ui#26]
I want to get the value that user send recently.I add a event to bind the '.comment-form'.But it happend after insert collection.So i can't get the value.Thank you.

**Comment by vjrj** [comment]
As a workaround, I'm using [meteor-collection-hooks] (https://github.com/matb33/meteor-collection-hooks):

```
  Comments._collection.after.insert(function (userId, comment) {
    console.log("Comment added");
  });
```

**Comment by alonprince** [comment]
When I reply one comment. It just update the document. Not insert.So I must add `Comments._collection.after.update`.And if I delete the reply.It is also a update behave.I should analyse the document and do some different things.

**Comment by bmustata** [comment]
Some kind of hooks system will be super useful in the future.

**Comment by matteodem** [comment]
This will not be provided by the package, but to make things easier, the update modifiers will be simplified see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/issues/50
