### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by matteodem** [ARKHAM-Enterprises/meteor-comments-ui#27]
Look for a new avatar package and use that for the commentsBox.

**Comment by Neruell** [comment]
utilities:avatar

Which is still the same giturl as bengott:avatar (https://github.com/bengott/meteor-avatar) 


"I've forked @bengott's Avatar package to take over maintenance until he has time to come back to it. -Sacha"

So basically renaming the used package should "solve" the issue, will just allow to use a more updated version of the same bengott package.

**Comment by matteodem** [comment]
Thanks for the information, I updated the package and released a new verison __0.2.9__
