### ISSUE TITLE
Embed Media Links (Youtube, Twitter and so on)

### ISSUE THREAD

**Issue by mayvn10** [ARKHAM-Enterprises/meteor-comments-ui#28]
Hi:

What's a good approach using this package on a custom template (Meteor 1.1.0.2) to render a Youtube (youtube.com or youtu.be) link paste into an iFrame so user's can play videos on the page that renders the custom template?

Thanks in advance.

**Comment by matteodem** [comment]
You can use custom templates for now: https://github.com/ARKHAM-Enterprises/meteor-comments-ui#templates. I think it's a cool thing to have in the package itself though

**Comment by mayvn10** [comment]
Hi @matteodem 

We are using a custom template, but how would you approach turning a youtube link into an iFrame embed?

Thanks.

**Comment by matteodem** [comment]
I'd save it separately into a "media" document field and have it be an object:

```
{
  "type": "youtube",
  "content": "http://youtube.com..."
}
```

And then when displaying the comment turn the link into an iframe.

**Comment by mayvn10** [comment]
Hi @matteodem 

When defining schemas:

```javascript
Comments.changeSchema(function (currentSchema) {
  currentSchema.image = { type: "youtube", content: "http://youtube.com/watch?*" };
});
```

Do you put these definitions in the server-side startup? Or the JS of the client-side template?

**Comment by matteodem** [comment]
I'd put it in both environments.

**Comment by tdmoneybanks** [comment]
Hi, have a similar feature and have an issue. How would I be able to change what is stored in the comment doc before it is inserted or updated (so I can parse the content for a youtube video and store its url in the doc). I first tried to use the collection-hooks package but couldn't get access to the collection object, which i see is defined under the exported comments object. Do you have any ideas on how to add to the insert/update actions to do this? Thanks in advance!

**Comment by mayvn10** [comment]
@matteodem any updates here? thanks in advance.

**Comment by matteodem** [comment]
I'll add event hooks to make this possible. There are collection hooks though https://atmospherejs.com/matb33/collection-hooks and with https://atmospherejs.com/dburles/mongo-collection-instances you can access every collection that is defined easily (see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/model.js#L3)

**Comment by matteodem** [comment]
This now possible in 1.0 with media analyzers https://github.com/ARKHAM-Enterprises/meteor-comments-ui#media
