### ISSUE TITLE
problem installing package with meteor 1.2

### ISSUE THREAD

**Issue by delay** [ARKHAM-Enterprises/meteor-comments-ui#29]
There is a problem with the latest version of meteor 1.2. 

meteor add arkham:comments-ui
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_2.
Constraints on package "less":
* less@=2.5.0_2 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@1.0.11 <- arkham:comments-ui 0.2.10

Package worked great for previous versions.  Thanks for the great package!

**Comment by LoeLobo** [comment]
You can get the working code from pull request #30.

**Comment by matteodem** [comment]
This is fixed with the latest version.
