### ISSUE TITLE
username is not showing for oauth users

### ISSUE THREAD

**Issue by pravinbashyal** [ARKHAM-Enterprises/meteor-comments-ui#31]
after commenting, the username is shown for users from local registration as there is username field. However users from oauth does not show their username in comment.

**Comment by matteodem** [comment]
Do you have a screenshot?

**Comment by pravinbashyal** [comment]
![2015-09-25-135728_1166x732_scrot](https://cloud.githubusercontent.com/assets/6494332/10095970/6ed40760-638d-11e5-80b3-535fcefd8ed8.png)

the comment is done by the user registered from local accounts package. However reply is done by oauth user.

**Comment by matteodem** [comment]
Please show me the oauth user document, might be that the username field isn't set on that user.

**Comment by pravinbashyal** [comment]
Yes the username field is not set. But that is oauth. Shouldn't it be
`username or profile.name`?

**Comment by matteodem** [comment]
probably, I'll have a look at this soonish

**Comment by matteodem** [comment]
This is fixed in the latest version `0.2.13`
