### ISSUE TITLE
Hide comment username / user 

### ISSUE THREAD

**Issue by almogdesign** [ARKHAM-Enterprises/meteor-comments-ui#32]
Is it possible to hide the username / user of the person that made the comment and then later on show based on different custom rules?

**Comment by matteodem** [comment]
What is the use case for this?

**Comment by almogdesign** [comment]
Let's say you have an object for sale, another user has some questions but you don't want to show their info until they either buy it or put down a deposit so they don't by pass the app and go directly to the buyer

**Comment by matteodem** [comment]
I think it should be possible to overide the simple-schema with `changeSchema` and then add the logic there to pre-validate certain conditions and either set an empty username or not if your app wants to display it.

**Comment by almogdesign** [comment]
Great, will give it a try once the notifications or hooks come out.

**Comment by matteodem** [comment]
wrong issue?

**Comment by almogdesign** [comment]
No, but can't use the package if I have no way to create in app notifications and email when a new comment or reply is created

**Comment by matteodem** [comment]
This is the issue for hiding usernames and so on, not for notifications, event hooks.

**Comment by almogdesign** [comment]
Yes I know I opened up another issue for that, I was saying now that I you can hide the username which is great I will wait for the other issue before I test it out

**Comment by matteodem** [comment]
aha got it! awesome
