### ISSUE TITLE
Package publishes all commenter's emails

### ISSUE THREAD

**Issue by chmac** [ARKHAM-Enterprises/meteor-comments-ui#37]
Firstly, thanks for an awesome package. Saved us a ton of time implementing this ourselves.

As I read [this](https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/model.js#L445) it looks like the plugin is publishing all commenter's email addresses. Not sure if that's a major issue today, I guess meteor isn't a huge target for spammers right now. But it might be worth mentioning in the readme that this is the behaviour. I'm happy to send a PR if you like.

**Comment by matteodem** [comment]
yeah, you're right. Feel free to create a PR to add it to the README. I also don't think that it's a problem now but it might get one later. Maybe it's not even needed, I'll create a new issue for that.

**Comment by matteodem** [comment]
As of 1.0 the published data is configurable https://github.com/ARKHAM-Enterprises/meteor-comments-ui#published-data
