### ISSUE TITLE
Dynamically loading comments

### ISSUE THREAD

**Issue by kerranm** [ARKHAM-Enterprises/meteor-comments-ui#40]
Hi have a simple application which has blog posts and comments. I'm using your plugin for the comments. When changing from one blog to another the comments don't associated to the current blog dont show without a hard refresh. It's like the comments aren't being reinitialized again.

Also, after changing blog posts and then leaving a comment, the comment disappears until the hard refresh.

**Comment by matteodem** [comment]
Do you have a reproduction repository?

**Comment by kerranm** [comment]
No I dont mate. Have you come across this problem before??

**Comment by matteodem** [comment]
I'll reopen this issue when you have a reproduction repo.
