### ISSUE TITLE
Add more overridable templates (e.g singleComment)

### ISSUE THREAD

**Issue by whiplashoo** [ARKHAM-Enterprises/meteor-comments-ui#42]
I have customised the default template as is suggested in the README, but I cannot find a way, to **include my own singleComment template**. The basic things I want to do is to exclude the avatar image from the template and align all the comment info on the same line, and I don't want to resort to using CSS and jQuery for that.

**Comment by matteodem** [comment]
Do you want a `commentTemplate` parameter that allows to change the template for a single comment?

**Comment by whiplashoo** [comment]
Yes exactly that. I ended up defining a `customSingleComment` template and defining again all the helpers the current default template has.

**Comment by matteodem** [comment]
This has been added in the last version `1.1.0`, see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/GUIDE.md
