### ISSUE TITLE
Publish/Subscribe and facebook pic problems

### ISSUE THREAD

**Issue by urco** [ARKHAM-Enterprises/meteor-comments-ui#44]
Hi,

I´m having some problems getting the facebook pic user profile when I remove autopublish package. If I login with my facebook user I can see right my facebook user profile in the comment, but when I logout, my facebook pic profile is changed by the img avatar by default... with autopublish installed  it working fine. I´m looking for some Meteor object to get all data from "comments" collection using publish/subscribe, but I can´t find anything in the documentation...
When I explore comments collection in mongo, I can see a field called "image" for each comment, but is empty in all comments... Where is stored the user pic profile in the collection? I´m a bit lost around this issue... some suggestion? Many thanks in advance. The package is really great by the way!

**Comment by matteodem** [comment]
What is the exact problem described in one or two sentences / what is it that you want to be achieved?
