### ISSUE TITLE
Exception while simulating the effect of invoking 'comments/count'

### ISSUE THREAD

**Issue by RaspberryBlack** [ARKHAM-Enterprises/meteor-comments-ui#45]
I'm getting this error which disappears when I restart Meteor; then everything works until I refresh the page.
I've just put in the comments as per docs, no custom templates, settings, schema changes or anything:
Am I missing something? How can I go about debugging this? (I'm new to Meteor)

template:
`<div class="comment-section">
    {{> commentsBox id=_id}}
</div>`

Packages:
accounts-password           1.1.4
aldeed:autoform             5.8.1
aldeed:collection2          2.8.0
aldeed:simple-schema        1.5.3
arkham:comments-ui          0.2.14
blaze-html-templates        1.0.1
cfs:gridfs                  0.0.33
cfs:standard-packages       0.5.9
dburles:collection-helpers  1.0.4
dburles:google-maps         1.1.5
ecmascript                  0.1.6*
es5-shim                    4.1.14
fourseven:scss              3.4.1
iron:router                 1.0.12
jquery                      1.11.4
mdg:geolocation             1.1.0*
meteor-base                 1.0.1
mobile-experience           1.0.1
momentjs:moment             2.11.1
mongo                       1.1.3
session                     1.1.1
standard-minifiers          1.0.2 
tracker                     1.0.9 
zurb:foundation-sites       6.1.2

Stack Trace:
Meteor.makeErrorType/errorClass@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:525:15
check@http://localhost:3000/packages/check.js?9c4972d3f4fe56cd455d3022e70b5195e642fc41:61:15
["comments/count"]@http://localhost:3000/packages/arkham_comments-ui.js?419d3591a620751f1206be4dec71c1d26e1df0cc:479:7
.apply/stubReturnValue<@http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3911:20
.withValue@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:971:17
.apply@http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3902:31
.call@http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3780:12
Template.commentsBox.rendered@http://localhost:3000/packages/arkham_comments-ui.js?419d3591a620751f1206be4dec71c1d26e1df0cc:1386:5
runTemplateHooks@http://localhost:3000/packages/aldeed_template-extension.js?198fda9390ae7785a7535751677cd8247508c9eb:417:5
templateExtensionMasterHook@http://localhost:3000/packages/aldeed_template-extension.js?198fda9390ae7785a7535751677cd8247508c9eb:366:5
fireCallbacks/<@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3330:9
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3671:12
fireCallbacks@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3326:3
Template.prototype.constructView/<@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3419:5
Blaze.View.prototype.onViewReady/fire/</<@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1780:11
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:2211:12
Blaze.View.prototype.onViewReady/fire/<@http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1779:9
Tracker._runFlush@http://localhost:3000/packages/tracker.js?7776276660c988c38fed448d8262b925dffb5bc3:523:11
onGlobalMessage@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:365:11
EventListener.handleEvent*usePostMessage@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:374:5
@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:403:3
@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:256:2
@http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:11:2

**Comment by matteodem** [comment]
Do you only have this error with Meteor? Also what OS do you use?

**Comment by RaspberryBlack** [comment]
Yes, only meteor. I'm on OSX 10.10 but it happens with my staging deployed app (meteor.com) as well. The stack trace above if from the browser but the server is spitting out something very similar.

**Comment by rorschach217** [comment]
i am using development environment as webstrom and windows 10

i used this code:
<div class="col-sm-6">
    <h3>User Review</h3>
    <div class="comment-section">
        {{> commentsBox id=_id }}
    </div>
</div>

and configured code:
Comments.ui.config({
    template: 'bootstrap' // default 'semantic-ui'
});

it gives exception like this in browser:
Exception while simulating the effect of invoking 'comments/count' errorClass {message: "Match error: Expected string, got object", path: "", sanitizedError: errorClass, errorType: "Match.Error"}errorType: "Match.Error"message: "Match error: Expected string, got object"path: ""sanitizedError: errorClassstack: (...)get stack: get stack()set stack: set stack()__proto__: Middle Error: Match error: Expected string, got object
    at check (http://localhost:3000/packages/check.js?9c4972d3f4fe56cd455d3022e70b5195e642fc41:61:15)
    at Meteor.methods.comments/count (http://localhost:3000/packages/arkham_comments-ui.js?2fcac61af1bd536c1deb35fe513ce8d1c95a7f80:478:7)
    at http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3911:25
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:971:17)
    at _.extend.apply (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3902:54)
    at _.extend.call (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3780:17)
    at Template.commentsBox.rendered (http://localhost:3000/packages/arkham_comments-ui.js?2fcac61af1bd536c1deb35fe513ce8d1c95a7f80:1385:12)
    at runTemplateHooks (http://localhost:3000/packages/aldeed_template-extension.js?198fda9390ae7785a7535751677cd8247508c9eb:417:10)
    at templateExtensionMasterHook (http://localhost:3000/packages/aldeed_template-extension.js?198fda9390ae7785a7535751677cd8247508c9eb:366:5)
    at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3330:22


and on terminal like this:
 Exception from sub comments/reference id pmmaWvR8CjMrqy7YE Error: Match error: Expected string, got object
     at check (packages/check/match.js:33:1)
     at [object Object].Comments.get.collection.find.referenceId (packages/arkham_comments-ui/lib/model.js:439:1)
     at [object Object].prepareOptions (packages/reywood_publish-composite/packages/reywood_publish-composite.js:440:1)
     at [object Object]._handler (packages/reywood_publish-composite/packages/reywood_publish-composite.js:408:1)
     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
     at livedata_server.js:548:43
 Sanitized and reported to the client as: Match failed [400]

 Exception while invoking method 'comments/count' Error: Match error: Expected string, got object
     at check (packages/check/match.js:33:1)
     at [object Object].Meteor.methods.comments/count (packages/arkham_comments-ui/lib/model.js:431:1)
     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
     at livedata_server.js:708:19

please give some advise to change something if needed.

thank you...

**Comment by matteodem** [comment]
Which version of meteor do you use?

**Comment by rorschach217** [comment]
I am using meteor 1.2.1

**Comment by matteodem** [comment]
Can you provide reproduction steps? Can you try creating a new app from start and seeing if the error also occurs?

**Comment by rorschach217** [comment]
ok I will try and then tell you..

thank you for consideration.

**Comment by RaspberryBlack** [comment]
I'm currently trying to do a repo to reproduce. For what it's worth, I've noticed a few things so far:
- I get tons of errors (template not found etc) when no accounts package is installed – which does make sense I suppose.
- I got the error when I didn't have the accounts-ui package installed but adding that package to my original project didn't fix the error there...

**Comment by matteodem** [comment]
okay, I'll create a new issue for that.

**Comment by RaspberryBlack** [comment]
I ended up implementing comments with the public api in the package (stripped down features though, I didn't need all of them) which works fine. It's probably not a big help but might work for anyone else looking for a workaround in the meantime.

**Comment by matteodem** [comment]
I'm working on v1 of this package and will have a look soon at if there are any problems when adding that version to an empty meteor project.

**Comment by matteodem** [comment]
Please test this behaviour with 1.0

**Comment by matteodem** [comment]
I've tested this locally and couldn't reproduce it, please provide a repository or steps with 1.0

**Comment by sajidhz1** [comment]
this error seems to be like there yet 
this is what I'm getting in my console 

Exception while simulating the effect of invoking 'comments/count' Object { stack: "Meteor.makeErrorType/errorClass@htt…", message: "Match error: Expected string, got u…", path: "", sanitizedError: Object, errorType: "Match.Error" } Meteor.makeErrorType/errorClass@http://localhost:3000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:566:20
require<.node_modules.meteor.check["match.js"]</exports.check@http://localhost:3000/packages/check.js?hash=63d7478b74cadc04d378bc2266ea8bd1bf6849d8:67:15
commentsCount@http://localhost:3000/packages/arkham_comments-ui.js?hash=39ba789aefd7ac4287f1dbc5bef3ffe8edebeabc:1046:7
.apply/stubReturnValue<@http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3973:20
.withValue@http://localhost:3000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:1077:17
.apply@http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3964:31

**Comment by matteodem** [comment]
Please create a new issue if this keeps persisting
