### ISSUE TITLE
Space is rendered inside `{{#markdown}}`

### ISSUE THREAD

**Issue by chmac** [ARKHAM-Enterprises/meteor-comments-ui#48]
There's a bug in the current version where the `{{#markdown}}` tag has whitespace inside it, which gets rendered as if it were part of the content.

**Comment by matteodem** [comment]
Great! gonna have a look later

**Comment by chmac** [comment]
@matteodem Any plans to push a new version with this fix? We've had to disable markdown comments until we get it through atmosphere...

**Comment by matteodem** [comment]
It's released now
