### ISSUE TITLE
Username Display Issue

### ISSUE THREAD

**Issue by ritchieng** [ARKHAM-Enterprises/meteor-comments-ui#54]
Hi, 

When a user comments, it grabs their email instead of their username. 

```
    {{#if templateIs 'bootstrap' }}
        <div class="media">
            <div class="media-left">
                {{> avatar userId=userId class="" }}
            </div>
            <div class="media-body comment">
                <h4 class="media-heading">{{user.displayName}} <small>{{createdAgo}}</small></h4>
```

The issue I see is in the template that uses {{user.displayName}} that is defined in model.js 

How do I fix it such that it grabs their names instead of their emails? 

This is my accounts.js file
```
Accounts.onCreateUser(function(options, user) {
  if (options.profile)
    user.profile = options.profile;

  var email = getUserEmail(user);
  if(email){
  	user.emailHash = CryptoJS.MD5(email.trim().toLowerCase()).toString();
  }
  
  return user;
});
```

**Comment by matteodem** [comment]
In the upcoming version it'll be possible to define yourself what "username" you want to display.

**Comment by ritchieng** [comment]
@matteodem Thanks. Really looking forward to that update.

**Comment by ritchieng** [comment]
@matteodem Thanks for the great update. I'm struggling with the implementation of defining the username to display for registered users. Currently the anonymous users function does it, but how about registered ones?

**Comment by matteodem** [comment]
You can define `publishUserFields` in the config call, which mirrors the `fields` when calling `find` on a mongo collection, see http://docs.meteor.com/#/full/publishandsubscribe. Also to define which username is displayed for all users, you can provide a `generateUsername` function which returns the string that identifies the user.
