### ISSUE TITLE
Template Customisation

### ISSUE THREAD

**Issue by ritchieng** [ARKHAM-Enterprises/meteor-comments-ui#57]
Hi,

I'm having issues making amendments to the template. Thanks in advance for helping. 

I'm trying to integrate star-rating (https://atmospherejs.com/barbatus/stars-rating). 

I added the custom template as a parameter. 

{{> commentsBox 
        id=post._id 
        boxTemplate="myComments"
     }}

Then proceeded to make a myComments template with the stars-rating package included but the comments system would stop working. Am I suppose to copy the whole template from a file from commentsBox.html then modify it? I tried it and it didn't work also, do I've to create an accompanying myComments js file and map the original code over?

**Comment by matteodem** [comment]
Can you show me how you structured your template?

**Comment by ritchieng** [comment]
I simply did 

<template name="myComments">
    {{> starsRating id='rating' star='\\f005' class='awesome' mutable=true}}
</template>

My intention is simple, I just wanted users to be able to rate with stars using the package when they comment.

**Comment by matteodem** [comment]
The template you're adding replaces the whole commentBox, as it says in the parameter: **box**Template. For now you need to copy the html for the comment box and replace the single comment templates with your own.

**Comment by matteodem** [comment]
see #42

**Comment by ritchieng** [comment]
I read the other issue. Basically I've to copy the HTML and redefine the all the helpers in the JS file right?  Thanks.
