### ISSUE TITLE
Loggedin Username

### ISSUE THREAD

**Issue by ritchieng** [ARKHAM-Enterprises/meteor-comments-ui#58]
Hi,

Currently, username for logged in users are displayed as their emails example "xx@gmail.com". All other comments are displayed by their usernames like "John Doe". 

Upon logging out, the logged in user will be displayed as "Matthew Carter" for example. I did not modify any template from this package.

This is not user-friendly currently because logged-in users might think they're being shown as their emails. They would only find out this is not so unless they log out. 

May I know a quick fix to this?

**Comment by digisarathi** [comment]
+1

**Comment by matteodem** [comment]
You can change which username is displayed by configuring `generateUsername`, so it's up to you what to display for logged in users https://github.com/ARKHAM-Enterprises/meteor-comments-ui#published-data.
