### ISSUE TITLE
Add custom fields to schema and submit form

### ISSUE THREAD

**Issue by abate** [ARKHAM-Enterprises/meteor-comments-ui#59]
Hi, I'd like to add a few custom fields to the comment form. I've added these fields to the schema : 

```
Comments.changeSchema (currentSchema) ->
  currentSchema.analysis =
    type: Schemas.LicenseAnalysis
    optional: true
  currentSchema
```

but know I'm not sure how to add it to the form. Which template should I override ? You mention in the readme how to customize the template to show a comment, but not how to submit a comment. Is this possible ?

**Comment by matteodem** [comment]
Yes this should be possible by using the `boxTemplate`, but right now it's rather complicated as you need to replace the whole markup logic. See #42 for implementing those templates

**Comment by abate** [comment]
Ok, so I added : 

```
  <div class="comment-section">
    {{> commentsBox id=atts.doc._id boxTemplate="LicenseComments"}}
  </div>
```
and I copied the relevant part of the template as "LicenseComments". I guess now I should override the "textarea" template as well that is defined in your "commentsTextarea"... but ... I'm not sure this is going to work, as I'm going to loose all associated helpers ... Correct ? Basically what is missing is something similar to "boxTemplate" to customize/extend the textarea template in the same way you do with the boxTemplate. Am I missing something ?

```
<template name="LicenseComments">
  <h3>{{commentsBoxTitle}}</h3>

  {{#if sessionGet 'loginAction'}}
    <div class="alert alert-warning" role="alert">You need to login to {{sessionGet 'loginAction'}}</div>
  {{/if}}

  {{> textarea }}

  <div class="media-list comments">
    {{#each comment}}
      {{> commentsSingleComment}}
    {{/each}}
  </div>

  {{#if hasMoreComments}}
    <button type="button" class="btn btn-success btn-lg btn-block loadmore-action">{{ take key='load-more' default='Load more comments' }}</button>
  {{/if}}
</template>
```

**Comment by matteodem** [comment]
Yes you're right, but the events would still work if you apply the right classes, see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/components/commentsTextarea/commentsTextarea.html and https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/components/commentsBox/commentsBox.js#L142 for the events logic

**Comment by abate** [comment]
ok, yes, I can recycle the events, but ultimately, what I want to do is not possible (directly) as the method add does not allow me to insert any other value except what you defined : https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/collections/methods/comments.js#L70 .

In the end my template use a snippet from the commentsTextare template, but even if i add an additional input element in the form, that is not going to be taken into consideration.

```
  {{#if currentUser }}
    <form class="{{#if reply}}reply-form{{else}}comment-form{{/if}}" role="form" action="">
      <div class="form-group">
      <!-- add here other input elements -->
        <textarea
                placeholder="{{ take key='placeholder-textarea' default='Join the discussion'}}"
                class="form-control {{#if reply}}create-reply{{else}}create-comment{{/if}}" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  {{/if}}
````

If you want to make the Comments collection (and the textarea template) extensible, you ultimately need to make the method add more generic. As it stands I don't think that what I want to do it possible.

Even if I try to catch the click/submit event of my form, I cannot even add any additional field to my comment as I don't have its id.

```
Template.LicenseComments.events
  'submit .comment-form': (e) ->
  # I don't have the id of the comment that I've just added
  # just the id of the original object 
```

I'm not sure how to solve this problem . If you have any insight, i'm all hears :)

**Comment by matteodem** [comment]
Yes you're right, there probably needs a way to hook into these events and make them extendable.

**Comment by abate** [comment]
I sent you a pull request #61 (work in progress) . But please tell me this is the right direction. I'm a bit of a beginner in JS ...

**Comment by abate** [comment]
ok, I think my patch is ready. Can you please have a look at it ?

I've also tried to extend the "commentSingleComment" template using something like
```{{> Template.dynamic template=Extend data=ExtendData}}``` to pass a custom template
and show the additional data, but I didn't get that far...

Thanks for this nice module !

**Comment by matteodem** [comment]
Cool work, we'll try our best to have a look at it soon.
