### ISSUE TITLE
small problem with autoform

### ISSUE THREAD

**Issue by abate** [ARKHAM-Enterprises/meteor-comments-ui#62]
I've another small problem. I'm using your module together with autoform. You can easily replace the submit template, but you are forced to pass the autoForm the _id of the parent as ''id'' to make it work. This is rather unfortunate as I cannot assign an arbitrary (and unique) id to my autoform to use it for example to attach a helper to it. Maybe using a different name, something like ''commentsID'' or ''referenceID'' would make it easier to use comments-ui with autoform.
  
```
    {{#autoForm collection=CommentsCollection id=id role="form" class=(formclass reply)}}
      <div class="form-group">
        {{> afFieldInput name="content" type="textarea"
            label="Comment"
            placeholder=(take key='placeholder-textarea' default='Join the discussion')
            class=(textareaclass reply) rows=3 }}
        {{> afQuickField name="analysis" }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    {{/autoForm}}
```

**Comment by matteodem** [comment]
What is the proposed solution for the problem you're having?

**Comment by abate** [comment]
simply using a different variable name that does not clash with autoform as "commentid" or "referenceid"

**Comment by matteodem** [comment]
I think this can be handled by using blaze functions such as `let` http://guide.meteor.com/blaze.html
