### ISSUE TITLE
Liking main document

### ISSUE THREAD

**Issue by ritchieng** [ARKHAM-Enterprises/meteor-comments-ui#63]
Hi, 

Is there a configuration where users can like/dislike the original post/document like in Disqus?

**Comment by matteodem** [comment]
Hi ritchie, that's not part of comments-ui but we can consider adding that, or re-using another package that provides this functionality.

**Comment by ritchieng** [comment]
@matteodem Thanks. A star or like/dislike system would be amazing!

**Comment by ritchieng** [comment]
@matteodem Was wondering if we were able to provide this functionality using https://atmospherejs.com/barbatus/stars-rating?

**Comment by matteodem** [comment]
Yes sure, feel free to test it out and see if it works well.

**Comment by matteodem** [comment]
This has been added in the latest version `1.1.0`, see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/GUIDE.md
