### ISSUE TITLE
Comments appearing on all posts

### ISSUE THREAD

**Issue by ritchieng** [ARKHAM-Enterprises/meteor-comments-ui#65]
Hi,

I managed to get this working for my "profile collection". However when I used it on an additional collection, the second collection had this issue: when I commented on a single document, it appeared on all of the documents in that collection. 

{{> commentsBox id=userId}} 

I used this line which worked for the first collection.

**Comment by ritchieng** [comment]
I got a fix for it if anyone is facing this issue. Do not tag it to the user. Tag it to the document id, so do this:

{{> commentsBox id=_id}}

**Comment by matteodem** [comment]
yes, the `id` parameter that you specify needs to be different for every document that you want to have different comments on.

**Comment by ritchieng** [comment]
Thanks! Really appreciate your responses on this package. Looking forward to future updates!
