### ISSUE TITLE
Multiple Templates Error on Custom Single Comments

### ISSUE THREAD

**Issue by mayvn10** [ARKHAM-Enterprises/meteor-comments-ui#66]
I'm creating a custom single comments template but the following error keeps appearing:

> Uncaught Error: There are multiple templates named 'commentsSingleComment'. Each template needs a unique name.

The structure goes as follows:

```
<template name="newsCommentBox">
    ...
    <div class="media-list comments">
        {{#each comment}}
            {{> commentsSingleComment}}
        {{/each}}
    </div>
    ...
</template>
```

```
<template name="commentsSingleComment">
    {{#if templateIs 'bootstrap' }}
    <div class="media">
    ...
            {{#if reply}}
                {{#each reply}}
                    {{> commentsSingleComment}}
                {{/each}}
            {{/if}}
    ...
    </div>
    {{/if}}
</template>
```

Why would this error be showing up even if I followed your example within the lib directory of this GitHub?

**Comment by mayvn10** [comment]
On another note, the "default template" link in the Customization area of the docs is a dead link:
https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/templates.html

So I followed the examples from the lib directory.

**Comment by matteodem** [comment]
Removed the dead links and will have a look at this shortly

**Comment by mayvn10** [comment]
@matteodem The links on Atmosphere JS are also outdated.

Did you see how the error was caused? I'm updating my code now using the template you gave and I'll let you know.

**Comment by mayvn10** [comment]
I tried different combinations of templates and it seems like you can create custom templates for the commentsBox and the commentsTextarea but not the commentsSingleComment.

Can this be fixed?

**Comment by ritchieng** [comment]
+1 See #42

**Comment by matteodem** [comment]
Please use the github features for upping topics.

**Comment by mayvn10** [comment]
@matteodem When do you think custom templates for commentsSingleComment will be added? Is there a timeline?

**Comment by matteodem** [comment]
In the next days probably, it's all already implemented in the `star-rating` branch, if you want to try it out locally. I'll probably go over it again and then release it soon.

**Comment by mayvn10** [comment]
Is the star rating feature similar to an upvote/downvote system?

**Comment by matteodem** [comment]
no, it's a 5 star rating system, by default it's still the liking system but you'll be able to switch if you want to.

**Comment by matteodem** [comment]
Checkout the latest version `1.1.0`, see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/GUIDE.md
