### ISSUE TITLE
export mediaService so it can be used in custom single comment

### ISSUE THREAD

**Issue by tdmoneybanks** [ARKHAM-Enterprises/meteor-comments-ui#67]
Hi, currently it requires some work arounds to make a custom single comment with this package. I have already done that work but there is one small change that is keeping me from being able to get media analyzers to work in this custom template. The mediaAnalyzer object is not exported from the package and so I am not able to access it within the helper of my custom template. Could you please add the mediaService object to the exported objects or scope it under the Comments object? 
Thanks and great work:)

**Comment by matteodem** [comment]
see #42

**Comment by tdmoneybanks** [comment]
i see. so is your suggestion just to wait/use my own analyzer until the custom single comment template is complete?

**Comment by matteodem** [comment]
I think I understood this issue wrongly, I'll probably make the mediaService part of the Public API.

**Comment by tdmoneybanks** [comment]
That would be great thanks

**Comment by mayvn10** [comment]
@matteodem good work on this package!

when will this enhancement be implemented?

**Comment by matteodem** [comment]
I'll try to have a look later today, feel free to add this yourself in a PR as it's a rather small change and I'm happy for every contribution we can get.

**Comment by matteodem** [comment]
It is now possible to retrieve the mediaService through the Public API: `Comments._mediaService`.
