### ISSUE TITLE
Count number of comments

### ISSUE THREAD

**Issue by ritchieng** [ARKHAM-Enterprises/meteor-comments-ui#68]
Hi, 

How do you access the collection and count the number of comments for each main ._id?

**Comment by matteodem** [comment]
You can access the collection with `Comments.getCollection()`, see https://github.com/ARKHAM-Enterprises/meteor-comments-ui#event-hooks

**Comment by ritchieng** [comment]
@matteodem 

I'm currently using simple https://github.com/percolatestudio/publish-counts to count. 

However, when I tried the following, I'm unable to count the comments of each main id. I believe it's because I'm unable to access the collection properly. 

Server: 
```
Meteor.publish('commentCount', function() {
    Counts.publish(this, 'comments', Comments.getCollection().find({
        replies: true
    }));
});
```

Client: 
`{{getPublishedCount 'comments'}}`

I can count the number of users correctly using my own collections (not related to your package but to show you it should work) in the following code.

Server
```
Meteor.publish('developerCount', function() {
    Counts.publish(this, 'developers', Profiles.find({
        status: "active"
    }));
});
```

Client
`{{getPublishedCount developers'}}
`

**Comment by matteodem** [comment]
I am not really sure what the problem is here and how it relates to comments-ui.

**Comment by ritchieng** [comment]
**What I'm trying to do**: retrieve the number of comments for each documentId
**Problem**: can't access the collection and the fields. 

**Normal access**:
`Collection.find() `

**Your documentation: **
`Comments.getCollection() `
`So Comments.getCollection().find()?`

**Comment by ritchieng** [comment]
Still finding a solution to check if the "content" region is true for the documentId. But I managed to access the collection in case anyone wants to count: 

Server:
Meteor.publish('commentCount', function() {
    Counts.publish(this, 'comments', Comments.getCollection().find({
        content: "wow" 
    }));
});

Client: 
Meteor.subscribe("commentCount");

Unfortunately it counts all "wow" when I want it to count the number of comments. Still working, maybe Matteo has some insights. Useful feature to monitor # of comments per documentId.

**Comment by matteodem** [comment]
If you want to count the number of comments then you need to call `.count()` on the docs and all the nested replies.

**Comment by ritchieng** [comment]
@matteodem For all the newbies, I managed to auto insert "active" comment field in the schema. Then now it's possible to count all comments. You can literally copy all the code and paste it in the respect files (server, client, and both). Please look at the revised code above with "JS" meaning place in JS file and "HTML" means place in "HTML" file. 

But the issue remains that I'm unable to come up with a solution to count per documentId. 

Example: for comments on documents Post 1 and Post 2.
I'm only able to count ALL comments for both posts, and not individually.

**Comment by ritchieng** [comment]
@matteodem How comments are associated with posts?

Someone recommended on meteor's forum that if we assume each comment has a post documentId associated with it. Pass documentId into your publish function, then use that to refine the returned cursor:

**Server**
```
Meteor.publish('postCommentCount', function(documentId) {
  check(documentId, String);
  Counts.publish(this, 'comments', Comments.getCollection().find({
    documentId
    status: 'active'
  }));
});
```

**Client**
`Meteor.subscribe('postCommentCount', documentId);`

**However, this does not work, the issue is with the documentId currently. **
