### ISSUE TITLE
TypeError After Updating to 1.0.2

### ISSUE THREAD

**Issue by mayvn10** [ARKHAM-Enterprises/meteor-comments-ui#70]
After updating to 1.0.2 today, the following error gets produced:

```
TypeError: Cannot call method 'config' of undefined
at lib/components/commentsBox/commentsBox.js:60:29
at Template.commentsSingleComment.helpers._.extend.hasLiked (lib/components/commentsBox/commentsBox.js:82:2)
at /.meteor/local/build/programs/server/packages/arkham_comments-ui.js:1540:4
at /.meteor/local/build/programs/server/packages/arkham_comments-ui.js:1626:3
at /.meteor/local/build/programs/server/boot.js:242:10
at Array.forEach (native)
at Function._.each._.forEach (/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)at /.meteor/local/build/programs/server/boot.js:137:5
```

All config and ui.config() settings are from the doc examples.

**Comment by oohaysmlm** [comment]
I'm having the same issue.  Shouldn't commentsBox.js be loaded only on the client side instead of in lib?

**Comment by mitar** [comment]
I can confirm this. It works with Meteor 1.3, but not with Meteor 1.2.1.

Here is a reproduction: https://github.com/mitar/meteor-comments-test

If I do inside the reproduction `meteor update` to get it to the latest Meteor version, then it works.

This is a blocker for me. :-(

**Comment by matteodem** [comment]
I'll try to have a look at this later today

**Comment by mitar** [comment]
I found the issue. Depending on the version from Atmosphere makes this issue. If I clone this repository (at latest master) into `packages` directory of my app everything works as expected.

Which version is published on the Atmosphere? From which git commit revision?

**Comment by matteodem** [comment]
Not sure, also tested it locally and it didn't work with `1.2.1`. There's a small quickfix that I would release later to prevent this error from happening.

**Comment by matteodem** [comment]
Just published `1.0.3` of comments-ui, please try it out.

**Comment by mitar** [comment]
I will not be able to do it at the moment, but fix seems to be so that it will address it, but probably also just hide it (the fact that client code gets loaded on the client).

**Comment by matteodem** [comment]
It's rather ugly but I did not really understand the underlying problem, as the `package.js` explicitely imported it on the client. Feel free to write into this issue if the error keeps occuring.
