### ISSUE TITLE
Changing Avatar

### ISSUE THREAD

**Issue by ivanthemeh** [ARKHAM-Enterprises/meteor-comments-ui#71]
I am having an issue with changing the default avatar. I have tried everything in the docs. Is there anything in 1.3 that would prevent this?

**Comment by mayvn10** [comment]
I'm running 1.2.1 and tried to define:
- a different default avatar URL
- a different user image path in a custom single comments template

In both cases, the image comes up blank or empty.

**Comment by matteodem** [comment]
Using `Comments.ui.config` as describe here doesn't work? https://github.com/ARKHAM-Enterprises/meteor-comments-ui#configurable-values

**Comment by mayvn10** [comment]
No, it stays empty.

I even added the gravatar.com and amazonaws.com to my browser policy. My case might be a little different than @ivanthemeh 

In any case, I think the general fix of a custom single comments template would be beneficial for all bugs like this long-term. What do you think @matteodem ?

**Comment by matteodem** [comment]
I'll see if I have time in the next days to implement those changes.

**Comment by matteodem** [comment]
How about changing the avatar with version `1.1.0`?

**Comment by mayvn10** [comment]
@matteodem using the configurable values?

**Comment by matteodem** [comment]
Yes, using `Comments.ui.config` to return an avatar url

**Comment by matteodem** [comment]
Tested this locally and it works with the latest version.
