### ISSUE TITLE
Conflict with aldeed:template-extension@3.4.3 (not satisfied by aldeed:template-extension 4.0.0)

### ISSUE THREAD

**Issue by derdaumen** [ARKHAM-Enterprises/meteor-comments-ui#73]
I would love to use this package, but a constraint on aldeed:template-extension@3.4.3 prevents me from doing so. Is this package incompatible with the new aldeed:template-extension@4.0.0 or could the dependency be updated?

    meteor add arkham:comments-ui
     => Errors while adding packages:             
                                              
    While selecting package versions:
    error: Conflict: Constraint aldeed:template-extension@3.4.3 is not satisfied by
    aldeed:template-extension 4.0.0.
    Constraints on package "aldeed:template-extension":
    * aldeed:template-extension@4.0.0 <- yogiben:admin 1.2.6
    * aldeed:template-extension@3.4.3 <- arkham:comments-ui 1.0.2`

**Comment by matteodem** [comment]
You can try checking it out in a local fork, I suspect that it's compatible.

**Comment by matteodem** [comment]
This will be resolved as soon as the `star-rating` is merged into master and released.

**Comment by matteodem** [comment]
This should be fixed in the last version `1.1.0`, see https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/GUIDE.md

**Comment by derdaumen** [comment]
It is fixed. Thank you!
