### ISSUE TITLE
Uncaught TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by mitar** [ARKHAM-Enterprises/meteor-comments-ui#81]
For some reason I am getting the following error at the following line:

```
userData._id && userData.salt && _this.subscribe('comments/anonymous', userData);
```

Not sure why this is happening. It is also happening only in one app. Maybe it has something with order of packages. Where is `userData` coming from anyway?

**Comment by matteodem** [comment]
It's coming from the `userService`, as in a `Session` variable. Do you have a small repro?

**Comment by mitar** [comment]
I couldn't make it. Can you point me to the place where it is set?

**Comment by matteodem** [comment]
https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/components/commentsBox/commentsBox.js#L104

https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/services/user.js#L45

https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/lib/services/user.js#L3

**Comment by mitar** [comment]
Yes, `Meteor.startup` seems to run after the template tries to be rendered.

**Comment by mitar** [comment]
I am using package-oriented app architecture. So everything I have is in packages. I resolved the issue by moving `api.use` of this package to the top of my `package.js` file, before depending on the `blaze-html-templates`.
