### ISSUE TITLE
Template is not defined / 1.0.3 / Meteor 1.2.1

### ISSUE THREAD

**Issue by cristopher29** [ARKHAM-Enterprises/meteor-comments-ui#87]
I installed the package to test it and get the following error. I don't know if I'm the only one who has this error.

arkham:comments-ui  version 1.0.3

```
ReferenceError: Template is not defined
at Template.commentsSingleComment.helpers._.extend.hasLiked (lib/components/commentsBox/commentsBox.js:91:1)
at C:\ProyectoMeteor\.meteor\local\build\programs\server\packages\arkham_comments-u
i.js:1546:4
at C:\ProyectoMeteor\.meteor\local\build\programs\server\packages\arkham_comments-u
i.js:1632:3
at C:\ProyectoMeteor\.meteor\local\build\programs\server\boot.js:242:10
at Array.forEach (native)
at Function._.each._.forEach (C:\Users\Equipo\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_
bundle\server-lib\node_modules\underscore\underscore.js:79:11)
```
```
Template.commentsSingleComment.helpers(_.extend(defaultCommentHelpers...
```

**Comment by matteodem** [comment]
Very weird, as templating is being required here https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/package.js#L19

**Comment by m-pokrovskii** [comment]
I have the same issue.

**Comment by matteodem** [comment]
Can you try executing `meteor add templating` to your project and see if that helps for now?

**Comment by m-pokrovskii** [comment]
I've just updated Meteor to 1.3. I will try it later.

**Comment by matteodem** [comment]
I cannot reproduce this error with `1.3` and the latest comments ui version.

**Comment by m-pokrovskii** [comment]
Seems to me, if meteor see a conflict with dependencies he's downloading the lower version to solve it. 
Cause i was able to use admin panel and your packages together, but after i've install them manually the meteor reject to  run due the dependency conflict.
