### ISSUE TITLE
Are Arkham Comments working with Meteor 1.3?

### ISSUE THREAD

**Issue by Method-X** [ARKHAM-Enterprises/meteor-comments-ui#90]
I apologize for opening this "issue" as it's probably just something I'm doing wrong. When I install this package all I get is the UI without any functionality. I created a test install just for Arkham, installed accounts-password and accounts-ui, pasted in...

```
<div class="comment-section">
    {{> commentsBox id=documentId}}
</div> 
```

...and it's just an input box that doesn't do anything. I'm properly logged in with accounts but Arkham doesn't work.

**Comment by DominikButz** [comment]
You need to make sure that that some data is bound to the template in which you add the div with the comment-section class. Comment objects need to be related to another js data object.  If the div is added without any context, then documentId is null. 

Therefore, it might not work if you don't have any object to which the comments are related. Maybe that's the reason why they don't appear. 
_id in the example below is the primary key of the data object to which the comments refer. For example a blog post, a photo or whatever.  _id is defined in my template in which I add the comment section. 

	<div class="comment-section">
			{{> commentsBox id=_id}}
		</div>

**Comment by Method-X** [comment]
@DominikButz 

In lib/collections/comments.js

```
// Create 'comments' database
ArkhamComments = new Mongo.Collection('arkham_comments');

// Allow logged in users access to 'comments' database
ArkhamComments.allow({
  insert: function(userId, doc) {
    return !!userId;
  },
  update: function(userId, doc) {
    return !!userId;
  }
});
```

In server/publications.js

```
//Comments database
Meteor.publish('arkham_comments', function() {
  return ArkhamComments.find();
});

//Single comments
Meteor.publish('single_arkham_comment', function(commentId) {
  return ArkhamComments.find({_id: commentId});
});
```
And finally:

```
// Subscribe to "comments" collection
Meteor.subscribe('arkham_comments');
```

I have also added both the insecure and autopublish packages with no luck. What is "`documentId`" supposed to be? I only somewhat know what I'm doing.

**Comment by Method-X** [comment]
I'm not going to lie... only about 20% of what you said makes any sense to me.

**Comment by DominikButz** [comment]
I removed autopublish and subscribed to articleComments. 

//server:
Meteor.publish('articleComments', function(docId) {
  return Comments.get(docId);
});

// client:
Template.[templateName].onCreated(function() {
	Meteor.subscribe('articleComments', Session.get('documentId'));
});

I set the documentId (or whatever you call it) when routing to my detail view (Session.set('documentId', this.params._id).  

Still, I can see all comments but not the replies to comments...

**Comment by Method-X** [comment]
@DominikButz I'm going to install meteor 1.2 and see if arkham comments work with that. I'll report back what happens.

**Comment by DominikButz** [comment]
Thanks, let me know if it is related to the Meteor version.

**Comment by matteodem** [comment]
Closing as it works with the latest Meteor release `1.3.2.4`.
