### ISSUE TITLE
Custom avatars

### ISSUE THREAD

**Issue by prathviraj080** [ARKHAM-Enterprises/meteor-comments-ui#92]
I've profile images for all the users and I'm storing it in `Meteor.users` collection. 
Is there any way I can display these URLs instead of default ones?

**Comment by matteodem** [comment]
Not sure why this is not implemented yet.

* Check if `utilities:avatar` pkg is still needed
* Add possibility to define custom avatar images

**Comment by delay** [comment]
The way I handled this since you can define a custom template for any part:  I made a custom singleComment template.  And altered the default template with this code.

`{{> commentsBox 
        id=post._id 
        singleCommentTemplate="singleComment"
    }}`

`<a class="avatar">
                        <div class="avatar"><img src="{{getAvatar}}" class="avatar-image" alt="avatar"></div>
                    </a>`

Then I created a helper.
`Template.singleComment.helpers({

    getAvatar: function() { 
        var user = Meteor.users.findOne(this.userId);
        var imageAvatar = Comments.ui.config().defaultAvatar;
        var customAvatar = user && user.profile && user.profile.customAvatar; //http://stackoverflow.com/questions/25758476/exception-in-template-helper-typeerror-cannot-read-property-profile-of-undef
        if (customAvatar === 1) {
            imageAvatar = "http://yourdomain.com/image/"+this.userId+".png";
        }
        return imageAvatar;
    }

});`

There is probably a better way to do this but that's how I handled it.

**Comment by matteodem** [comment]
Yeah for now that's a solution that works, it'd be cool though to have something that's easily configurable.

**Comment by prathviraj080** [comment]
+1 @delay

**Comment by matteodem** [comment]
This is possible now over the public API https://github.com/ARKHAM-Enterprises/meteor-comments-ui/blob/master/GUIDE.md#published-data
